/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteSettingsRouteImport } from './routes/_site/settings'
import { Route as SitePostsHandleRouteImport } from './routes/_site/posts/$handle'
import { Route as SiteSettingsDeveloperRouteImport } from './routes/_site/settings/developer'
import { Route as SiteSettingsGeneralRouteImport } from './routes/_site/settings/general'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPublicPostsRouteImport } from './routes/api/public/posts'
import { Route as ApiPublicTopicsRouteImport } from './routes/api/public/topics'

const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/_site/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSettingsRoute = SiteSettingsRouteImport.update({
  id: '/_site/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitePostsHandleRoute = SitePostsHandleRouteImport.update({
  id: '/_site/posts/$handle',
  path: '/posts/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSettingsDeveloperRoute = SiteSettingsDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => SiteSettingsRoute,
} as any)
const SiteSettingsGeneralRoute = SiteSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SiteSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPostsRoute = ApiPublicPostsRouteImport.update({
  id: '/api/public/posts',
  path: '/api/public/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTopicsRoute = ApiPublicTopicsRouteImport.update({
  id: '/api/public/topics',
  path: '/api/public/topics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/settings': typeof SiteSettingsRouteWithChildren
  '/': typeof SiteIndexRoute
  '/posts/$handle': typeof SitePostsHandleRoute
  '/settings/developer': typeof SiteSettingsDeveloperRoute
  '/settings/general': typeof SiteSettingsGeneralRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/posts': typeof ApiPublicPostsRoute
  '/api/public/topics': typeof ApiPublicTopicsRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/settings': typeof SiteSettingsRouteWithChildren
  '/': typeof SiteIndexRoute
  '/posts/$handle': typeof SitePostsHandleRoute
  '/settings/developer': typeof SiteSettingsDeveloperRoute
  '/settings/general': typeof SiteSettingsGeneralRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/posts': typeof ApiPublicPostsRoute
  '/api/public/topics': typeof ApiPublicTopicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_site/settings': typeof SiteSettingsRouteWithChildren
  '/_site/': typeof SiteIndexRoute
  '/_site/posts/$handle': typeof SitePostsHandleRoute
  '/_site/settings/developer': typeof SiteSettingsDeveloperRoute
  '/_site/settings/general': typeof SiteSettingsGeneralRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/posts': typeof ApiPublicPostsRoute
  '/api/public/topics': typeof ApiPublicTopicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/settings'
    | '/'
    | '/posts/$handle'
    | '/settings/developer'
    | '/settings/general'
    | '/api/auth/$'
    | '/api/public/posts'
    | '/api/public/topics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/settings'
    | '/'
    | '/posts/$handle'
    | '/settings/developer'
    | '/settings/general'
    | '/api/auth/$'
    | '/api/public/posts'
    | '/api/public/topics'
  id:
    | '__root__'
    | '/_auth/login'
    | '/_auth/register'
    | '/_site/settings'
    | '/_site/'
    | '/_site/posts/$handle'
    | '/_site/settings/developer'
    | '/_site/settings/general'
    | '/api/auth/$'
    | '/api/public/posts'
    | '/api/public/topics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  SiteSettingsRoute: typeof SiteSettingsRouteWithChildren
  SiteIndexRoute: typeof SiteIndexRoute
  SitePostsHandleRoute: typeof SitePostsHandleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicPostsRoute: typeof ApiPublicPostsRoute
  ApiPublicTopicsRoute: typeof ApiPublicTopicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/settings': {
      id: '/_site/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SiteSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/posts/$handle': {
      id: '/_site/posts/$handle'
      path: '/posts/$handle'
      fullPath: '/posts/$handle'
      preLoaderRoute: typeof SitePostsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/settings/developer': {
      id: '/_site/settings/developer'
      path: '/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof SiteSettingsDeveloperRouteImport
      parentRoute: typeof SiteSettingsRoute
    }
    '/_site/settings/general': {
      id: '/_site/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SiteSettingsGeneralRouteImport
      parentRoute: typeof SiteSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/posts': {
      id: '/api/public/posts'
      path: '/api/public/posts'
      fullPath: '/api/public/posts'
      preLoaderRoute: typeof ApiPublicPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/topics': {
      id: '/api/public/topics'
      path: '/api/public/topics'
      fullPath: '/api/public/topics'
      preLoaderRoute: typeof ApiPublicTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteSettingsRouteChildren {
  SiteSettingsDeveloperRoute: typeof SiteSettingsDeveloperRoute
  SiteSettingsGeneralRoute: typeof SiteSettingsGeneralRoute
}

const SiteSettingsRouteChildren: SiteSettingsRouteChildren = {
  SiteSettingsDeveloperRoute: SiteSettingsDeveloperRoute,
  SiteSettingsGeneralRoute: SiteSettingsGeneralRoute,
}

const SiteSettingsRouteWithChildren = SiteSettingsRoute._addFileChildren(
  SiteSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  SiteSettingsRoute: SiteSettingsRouteWithChildren,
  SiteIndexRoute: SiteIndexRoute,
  SitePostsHandleRoute: SitePostsHandleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicPostsRoute: ApiPublicPostsRoute,
  ApiPublicTopicsRoute: ApiPublicTopicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
